version: '3.8'
services:
  mongodb-user:
    image: mongo:4.4
    container_name: mongodb-user
    ports:
      - "27018:27017"
    volumes:
      - ./data/user-db:/data/db
    environment:
      MONGO_INITDB_DATABASE: users

  mongodb-restaurant:
    image: mongo:4.4
    container_name: mongodb-restaurant
    ports:
      - "27019:27017"
    volumes:
      - ./data/restaurant-db:/data/db
    environment:
      MONGO_INITDB_DATABASE: restaurants

  kafka:
    image: bitnami/kafka:latest
    container_name: data236-lab2-orders
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

volumes:
  user-db:
    driver: local
  restaurant-db:
    driver: local