apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP  # Explicitly set (default, but good practice)
  selector:
    app: kafka
  ports:
  - name: kafka-internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  # Only include 9093 if you actually need it in your Kafka config
  - name: kafka-external
    port: 9093
    targetPort: 9093
    protocol: TCP
  clusterIP: None  # Headless service for direct pod access